spring:
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://nexfit-admin:newPassw0rd@ac-m1hrvkw-shard-00-00.voszrn1.mongodb.net:27017,ac-m1hrvkw-shard-00-01.voszrn1.mongodb.net:27017,ac-m1hrvkw-shard-00-02.voszrn1.mongodb.net:27017/nexfit?ssl=true&authSource=admin&retryWrites=true&w=majority}
      database: ${MONGODB_DATABASE:nexfit}
      auto-index-creation: true

server:
  port: ${SERVER_PORT:8080}
  servlet:
    context-path: /api/v1

aws:
  s3:
    prefix: ${AWS_S3_PREFIX:prod}

launchdarkly:
  enabled: ${LAUNCHDARKLY_ENABLED:true}

media:
  sync:
    on-startup: ${MEDIA_SYNC_ON_STARTUP:false}
